### ISSUE TITLE
fix: dto필요없는거 제거, 코드 리팩토링

### ISSUE THREAD

**Issue by kimtuna** [Team-GitBox/gitbox-backend#11]
# Title

- title

# TODO

- [x] dto에 필요없는 함수 제거
- [x] 토큰 받아오는 방식 최신화
- [x] controller에 있는 불필요한 작업들 서비스로 옮기기
- [x] 에러 메세지 한글화
- [x] delete member쪽에 이메일 id값 말고 이메일 자체로 바꾸기
- [x] delete member쪽 왜인지 모르는데 버그 있는 듯 확인 필요
- [x] delete workspace 할 때, 해당 워크스페이스 멤버도 다 삭제

# etc

- nothing
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
