### ISSUE TITLE
️refactor: 휴지통 기능 수정

### ISSUE THREAD

**Issue by singsangssong** [Team-GitBox/gitbox-backend#18]
# Title

- title : 휴지통 기능 수정하기

# TODO

- [x] '파일 여러 개 삭제/복원하기' 기능 없애기
- [x] 단일 파일 삭제 -> 파일 아이디값 하나만 받아도 전체 노드가 삭제되도록 구현
- [x] 복윈도 2번처럼 마찬가지로 구현
- [x] 휴지통 파일 조회하기 -> 파일 entity에서 뿌리노드의 id값만 가져다주기

# etc

- @kimday0326 @kimtuna 
- 이거 윤형이랑 얘기했고 여러 파일 삭제/복원하기는 없애기로 했어용 
- 특히 '휴지통에 삭제/복원하기' 기능들이 FE에서  fileId값만 받으면 id값에 해당하는 파일(노드 하나)만 삭제하도록 되어있어서 파일 하나의 전체 노드를 삭제하지 않도록 되어있더라구요... 기능 수정하고 오늘 3시전까지 다 만들어둘게요..
