### ISSUE TITLE
feat: history 기능 개발 + 에러 추가 및 한글 변경

### ISSUE THREAD

**Issue by singsangssong** [Team-GitBox/gitbox-backend#5]
# Title

- title

# TODO

- [x] history 기능 개발
- [x] 맴버, pullRequest, history 기능에서 에러메세지 추가하기
- [x] 에러msg 한글로 통일
- [x] pullRequest Enum값 수정하기
- [x] BaseEntity 연결하기

# etc

- nothing
